---
- name:
  hosts: localhost
  roles:
    - proxy
    - dns

  tasks:

    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: "yes"
        state: present
        reload: "yes"

    - name: "Install Nginx"
      apt:
        name: "nginx"
        state: latest
        update_cache: "yes"

    - name: "Download loganalyzer"
      uri:
        url: http://download.adiscon.com/loganalyzer/loganalyzer-4.1.11.tar.gz
        dest: /tmp/loganalyzer-4.1.11.tar.gz
        status_code: 200
